server:
  port: 8801

eureka:
  instance: trying-discoryServer-001
  client:
    serviceUrl:
      defaultZone: http://localhost:8802/eureka/,http://localhost:8803/eureka/
    register-with-eureka: false
