
server:
  port: 8803

eureka:
  instance: trying-discoryServer-003
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8801/eureka/,http://localhost:8802/eureka/
