server:
  port: 8802

eureka:
  instance: trying-discoryServer-002
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8801/eureka/,http://localhost:8803/eureka/
